### PR TITLE
Add output of the program to output.txt and Capitalize structs' first letter

### PR DESCRIPTION
**Pull request by ErdemOzgen**
https://refactoring.guru/design-patterns/decorator/go/example ==> There is no output in txt file
Capitalize structs' first letter ==> The structs aren't visible, but you can still pass values of those types
to functions in other packages. It is okay for this example but good for best practice.

### CODE REVIEW

**Comment by ErdemOzgen** [comment]
@neochief and @AnhellO , Would you please check this out ?

**Comment by neochief** [comment]
Thank you for the pull request. I cherry-picked the output text already; thank you for that.

However, I'm not sure why the capitalization change is needed? All the rest of the code follows a different convention. Since I'm not the original author of this code, I won't change the case unless you guys explain why the change is needed here but not needed in the rest of the examples.

**Comment by neochief** [comment]
Let me add that I appreciate any help. And if someone wants to do a major cleanup in this repository, I'm all up for it, but I'd like it either to be done to all files or none at all.

**Comment by ErdemOzgen** [comment]
I believe we can change capital letters for the rest of the examples. This common trap starts for Golang newcomers. In Go, using a capital letter for any package object (type, variable, or function) will make it exported automatically that has been forgotten by newcomers. For a design pattern guide like this, we can use this pattern to avoid them fail into this trap. If you wish I can change rest of code for every example ?

**Comment by neochief** [comment]
@ErdemOzgen In this case, please do it for all files. Thanks a lot for the help, Erdem!

**Comment by ErdemOzgen** [comment]
With my pleasure. Thanks a lot

**Comment by ErdemOzgen** [comment]
@neochief  I have been finished for rest of code. Waiting for merge.

**Comment by neochief** [comment]
Thank you for a great job! I have merged all the changes. I'll update the code on the website soon as well. Thanks a lot, man!

**Comment by ErdemOzgen** [comment]
It was my pleasure.

**Pull request merged**
